import uuid
from sqlalchemy import String, Boolean, ForeignKey, Text, UniqueConstraint
from sqlalchemy.dialects.postgresql import UUID, JSONB
from sqlalchemy.orm import Mapped, mapped_column, relationship
from app.database import Base, TimestampMixin


class Site(Base, TimestampMixin):
    __tablename__ = "sites"
    __table_args__ = (UniqueConstraint("tenant_id", "domain"),)

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    tenant_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("tenants.id"), index=True)
    domain: Mapped[str] = mapped_column(String(255), nullable=False)
    display_name: Mapped[str | None] = mapped_column(String(255))

    yandex_webmaster_host_id: Mapped[str | None] = mapped_column(String(255))
    yandex_metrica_counter_id: Mapped[str | None] = mapped_column(String(50))
    yandex_oauth_token: Mapped[str | None] = mapped_column(Text)  # encrypted at rest

    operating_mode: Mapped[str] = mapped_column(String(20), default="readonly")
    is_active: Mapped[bool] = mapped_column(Boolean, default=True)
    settings: Mapped[dict] = mapped_column(JSONB, default=lambda: {})

    vertical: Mapped[str] = mapped_column(String(32), nullable=False, default="tourism", server_default="tourism")
    business_model: Mapped[str] = mapped_column(String(48), nullable=False, default="tour_operator", server_default="tour_operator")

    # Target Demand Map (Phase A) — user-declared services/geo/competitor brands.
    # Populated via psql/SQL during early adoption; no UI in Phase A.
    target_config: Mapped[dict] = mapped_column(
        JSONB,
        nullable=False,
        default=lambda: {},
        server_default="{}",
    )

    # Phase F — Draft Profile Builder staging column. Auto-generated by
    # the draft_profile builder; committed to target_config only on
    # explicit admin/user approval. Nothing downstream reads this yet.
    target_config_draft: Mapped[dict] = mapped_column(
        JSONB,
        nullable=False,
        default=lambda: {},
        server_default="{}",
    )

    # Этап 1 — conversational onboarding state.
    # onboarding_step walks through: pending_analyze → confirm_business →
    # confirm_products → confirm_competitors → confirm_queries →
    # confirm_positions → confirm_plan → confirm_kpi → active.
    # Celery tasks check for "active" before running the nightly pipeline.
    onboarding_step: Mapped[str] = mapped_column(
        String(32), nullable=False, default="pending_analyze",
        server_default="pending_analyze",
    )
    understanding: Mapped[dict] = mapped_column(
        JSONB, nullable=False, default=lambda: {}, server_default="{}",
    )
    competitor_domains: Mapped[list] = mapped_column(
        JSONB, nullable=False, default=list, server_default="[]",
    )
    kpi_targets: Mapped[dict] = mapped_column(
        JSONB, nullable=False, default=lambda: {}, server_default="{}",
    )

    tenant = relationship("Tenant", back_populates="sites")
